/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.footballleagues.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.codegen.footballleagues.FootballLeagues;
import org.jooq.codegen.footballleagues.Keys;
import org.jooq.codegen.footballleagues.tables.records.TeamRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Team extends TableImpl<TeamRecord> {

    private static final long serialVersionUID = -982512136;

    /**
     * The reference instance of <code>football_leagues.team</code>
     */
    public static final Team TEAM = new Team();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TeamRecord> getRecordType() {
        return TeamRecord.class;
    }

    /**
     * The column <code>football_leagues.team.id</code>.
     */
    public final TableField<TeamRecord, UShort> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>football_leagues.team.name</code>.
     */
    public final TableField<TeamRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>football_leagues.team.tla</code>.
     */
    public final TableField<TeamRecord, String> TLA = createField(DSL.name("tla"), org.jooq.impl.SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>football_leagues.team.short_name</code>.
     */
    public final TableField<TeamRecord, String> SHORT_NAME = createField(DSL.name("short_name"), org.jooq.impl.SQLDataType.VARCHAR(25), this, "");

    /**
     * The column <code>football_leagues.team.area_name</code>.
     */
    public final TableField<TeamRecord, String> AREA_NAME = createField(DSL.name("area_name"), org.jooq.impl.SQLDataType.VARCHAR(25), this, "");

    /**
     * The column <code>football_leagues.team.email</code>.
     */
    public final TableField<TeamRecord, String> EMAIL = createField(DSL.name("email"), org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * Create a <code>football_leagues.team</code> table reference
     */
    public Team() {
        this(DSL.name("team"), null);
    }

    /**
     * Create an aliased <code>football_leagues.team</code> table reference
     */
    public Team(String alias) {
        this(DSL.name(alias), TEAM);
    }

    /**
     * Create an aliased <code>football_leagues.team</code> table reference
     */
    public Team(Name alias) {
        this(alias, TEAM);
    }

    private Team(Name alias, Table<TeamRecord> aliased) {
        this(alias, aliased, null);
    }

    private Team(Name alias, Table<TeamRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Team(Table<O> child, ForeignKey<O, TeamRecord> key) {
        super(child, key, TEAM);
    }

    @Override
    public Schema getSchema() {
        return FootballLeagues.FOOTBALL_LEAGUES;
    }

    @Override
    public Identity<TeamRecord, UShort> getIdentity() {
        return Keys.IDENTITY_TEAM;
    }

    @Override
    public UniqueKey<TeamRecord> getPrimaryKey() {
        return Keys.KEY_TEAM_PRIMARY;
    }

    @Override
    public List<UniqueKey<TeamRecord>> getKeys() {
        return Arrays.<UniqueKey<TeamRecord>>asList(Keys.KEY_TEAM_PRIMARY, Keys.KEY_TEAM_NAME, Keys.KEY_TEAM_TLA);
    }

    @Override
    public Team as(String alias) {
        return new Team(DSL.name(alias), this);
    }

    @Override
    public Team as(Name alias) {
        return new Team(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Team rename(String name) {
        return new Team(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Team rename(Name name) {
        return new Team(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<UShort, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
