/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.footballleagues;


import java.util.Arrays;
import java.util.List;

import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = 1040707617;

    /**
     * The reference instance of <code>DEFAULT_CATALOG</code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     * The schema <code>football_leagues</code>.
     */
    public final FootballLeagues FOOTBALL_LEAGUES = FootballLeagues.FOOTBALL_LEAGUES;

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        return Arrays.<Schema>asList(
            FootballLeagues.FOOTBALL_LEAGUES);
    }
}
