/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.footballleagues;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.codegen.footballleagues.tables.Competition;
import org.jooq.codegen.footballleagues.tables.Player;
import org.jooq.codegen.footballleagues.tables.Team;
import org.jooq.codegen.footballleagues.tables.TeamCompetition;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FootballLeagues extends SchemaImpl {

    private static final long serialVersionUID = 2016381075;

    /**
     * The reference instance of <code>football_leagues</code>
     */
    public static final FootballLeagues FOOTBALL_LEAGUES = new FootballLeagues();

    /**
     * The table <code>football_leagues.competition</code>.
     */
    public final Competition COMPETITION = Competition.COMPETITION;

    /**
     * The table <code>football_leagues.player</code>.
     */
    public final Player PLAYER = Player.PLAYER;

    /**
     * The table <code>football_leagues.team</code>.
     */
    public final Team TEAM = Team.TEAM;

    /**
     * The table <code>football_leagues.team_competition</code>.
     */
    public final TeamCompetition TEAM_COMPETITION = TeamCompetition.TEAM_COMPETITION;

    /**
     * No further instances allowed
     */
    private FootballLeagues() {
        super("football_leagues", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Competition.COMPETITION,
            Player.PLAYER,
            Team.TEAM,
            TeamCompetition.TEAM_COMPETITION);
    }
}
