/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.footballleagues;


import org.jooq.codegen.footballleagues.tables.Competition;
import org.jooq.codegen.footballleagues.tables.Player;
import org.jooq.codegen.footballleagues.tables.Team;
import org.jooq.codegen.footballleagues.tables.TeamCompetition;


/**
 * Convenience access to all tables in football_leagues
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>football_leagues.competition</code>.
     */
    public static final Competition COMPETITION = Competition.COMPETITION;

    /**
     * The table <code>football_leagues.player</code>.
     */
    public static final Player PLAYER = Player.PLAYER;

    /**
     * The table <code>football_leagues.team</code>.
     */
    public static final Team TEAM = Team.TEAM;

    /**
     * The table <code>football_leagues.team_competition</code>.
     */
    public static final TeamCompetition TEAM_COMPETITION = TeamCompetition.TEAM_COMPETITION;
}
